default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_token_system_development

test:
  <<: *default
  database: food_token_system_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>